r-ml:
    build:
        context: .
        dockerfile: Dockerfile-r-ml
        target: r-ml
    image: landeranalytics/r-ml
    container_name: r-ml
    tty: true
    stdin_open: true
    runtime: nvidia
    ports:
        - "8787:8787"
    environment:
        - PASSWORD=badpassword
